// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// VCS coverage exclude_file
module ram_64x6(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [5:0] R0_addr,
  input        R0_en,
               R0_clk,
  output [5:0] R0_data,
  input  [5:0] W0_addr,
  input        W0_en,
               W0_clk,
  input  [5:0] W0_data
);

  reg [5:0] Memory[0:63];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [6:0] i = 7'h0; i < 7'h40; i += 7'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i[5:0]] = _RANDOM_MEM[5:0];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 6'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue64_UInt6(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input        clock,	// <stdin>:65:11, :145:11, :226:11, :306:11
               reset,	// <stdin>:66:11, :146:11, :227:11, :307:11
               io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [5:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input        io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output       io_deq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [5:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [5:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [5:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       empty = ptr_match & ~maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :261:{25,28}
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// <stdin>:65:11, :145:11, :226:11, :306:11
    if (reset) begin	// <stdin>:65:11, :145:11, :226:11, :306:11
      enq_ptr_value <= 6'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 6'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// <stdin>:65:11, :145:11, :226:11, :306:11
      automatic logic do_deq = io_deq_ready & ~empty;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :261:25, :285:19
      if (do_enq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        enq_ptr_value <= enq_ptr_value + 6'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        deq_ptr_value <= deq_ptr_value + 6'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][5:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][11:6];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][12];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_64x6 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
  assign io_deq_valid = ~empty;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :261:25, :285:19
endmodule

module IdFreeList(	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
  input        clock,	// <stdin>:116:11, :277:11
               reset,	// <stdin>:117:11, :278:11
               enq_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:20:15
  input  [5:0] enq_bits,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:20:15
  input        deq_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:21:15
  output       deq_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:21:15
  output [5:0] deq_bits	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:21:15
);

  wire       _qIndex_io_deq_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:23:30
  wire [5:0] _qIndex_io_deq_bits;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:23:30
  reg  [6:0] rIndexSent;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:24:35
  always @(posedge clock) begin	// <stdin>:116:11, :277:11
    if (reset)	// <stdin>:116:11, :277:11
      rIndexSent <= 7'h0;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:24:35
    else if (rIndexSent[6] | ~deq_ready) begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:24:35, :28:42, :38:21, src/main/scala/chext/util/BitOps.scala:82:10
    end
    else	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:24:35, :28:42, :38:21
      rIndexSent <= rIndexSent + 7'h1;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:24:35, :39:32
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
    `ifdef FIRRTL_BEFORE_INITIAL	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
      `FIRRTL_BEFORE_INITIAL	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
      automatic logic [31:0] _RANDOM[0:0];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
      `ifdef INIT_RANDOM_PROLOG_	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
        `INIT_RANDOM_PROLOG_	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
        rIndexSent = _RANDOM[/*Zero width*/ 1'b0][6:0];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15, :24:35
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
      `FIRRTL_AFTER_INITIAL	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue64_UInt6 qIndex (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:23:30
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (enq_valid),
    .io_enq_bits  (enq_bits),
    .io_deq_ready (rIndexSent[6] & deq_ready),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:24:35, :28:42, :33:25, src/main/scala/chext/elastic/Connect.scala:10:18, src/main/scala/chext/util/BitOps.scala:82:10
    .io_deq_valid (_qIndex_io_deq_valid),
    .io_deq_bits  (_qIndex_io_deq_bits)
  );
  assign deq_valid = ~(rIndexSent[6]) | _qIndex_io_deq_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15, :23:30, :24:35, :28:42, :35:15, src/main/scala/chext/elastic/Connect.scala:11:16, src/main/scala/chext/util/BitOps.scala:82:10
  assign deq_bits = rIndexSent[6] ? _qIndex_io_deq_bits : rIndexSent[5:0];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:15:15, :23:30, :24:35, :28:42, :36:14, src/main/scala/chext/elastic/Connect.scala:12:15, src/main/scala/chext/util/BitOps.scala:82:10
endmodule

module IdList(	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:44:15
  input        clock,	// <stdin>:196:11, :357:11
               reset,	// <stdin>:197:11, :358:11
               enq_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:49:15
  input  [5:0] enq_bits,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:49:15
  input        deq_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:50:15
  output [5:0] deq_bits	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:50:15
);

  Queue64_UInt6 qIndex (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:52:30
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (enq_valid),
    .io_enq_bits  (enq_bits),
    .io_deq_ready (deq_ready),
    .io_deq_valid (/* unused */),
    .io_deq_bits  (deq_bits)
  );
endmodule

// VCS coverage exclude_file
module mem_64x67(	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  input  [5:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [66:0] R0_data,
  input  [5:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [66:0] W0_data
);

  reg [66:0] Memory[0:63];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  always @(posedge W0_clk) begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
    if (W0_en & 1'h1)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
      Memory[W0_addr] <= W0_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
    reg [95:0] _RANDOM_MEM;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
    initial begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
      `INIT_RANDOM_PROLOG_	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
      `ifdef RANDOMIZE_MEM_INIT	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
        for (logic [6:0] i = 7'h0; i < 7'h40; i += 7'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h60; j += 7'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
          end	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
          Memory[i[5:0]] = _RANDOM_MEM[66:0];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
        end	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 67'bx;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
endmodule

module SyncWriteElasticReadMemory(	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15
  input         clock,	// <stdin>:212:11
                io_wrEn,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input  [5:0]  io_wrAddr,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input  [63:0] io_wrData_data,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input  [1:0]  io_wrData_resp,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input         io_wrData_last,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  output        io_rdReq_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input         io_rdReq_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input  [5:0]  io_rdReq_bits,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input         io_rdResp_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  output        io_rdResp_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  output [63:0] io_rdResp_bits_data,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  output [1:0]  io_rdResp_bits_resp,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  output        io_rdResp_bits_last	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
);

  wire [66:0] _mem_ext_R0_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  mem_64x67 mem_ext (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
    .R0_addr (io_rdReq_bits),
    .R0_en   (1'h1),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .W0_addr (io_wrAddr),
    .W0_en   (io_wrEn),
    .W0_clk  (clock),
    .W0_data ({io_wrData_last, io_wrData_resp, io_wrData_data})	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  );
  assign io_rdReq_ready = io_rdResp_ready;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15
  assign io_rdResp_valid = io_rdReq_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15
  assign io_rdResp_bits_data = _mem_ext_R0_data[63:0];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15, :119:18
  assign io_rdResp_bits_resp = _mem_ext_R0_data[65:64];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15, :119:18
  assign io_rdResp_bits_last = _mem_ext_R0_data[66];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15, :119:18
endmodule

// VCS coverage exclude_file
module mem_64x34(	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  input  [5:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [33:0] R0_data,
  input  [5:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [33:0] W0_data
);

  reg [33:0] Memory[0:63];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  always @(posedge W0_clk) begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
    if (W0_en & 1'h1)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
      Memory[W0_addr] <= W0_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
    reg [63:0] _RANDOM_MEM;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
    initial begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
      `INIT_RANDOM_PROLOG_	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
      `ifdef RANDOMIZE_MEM_INIT	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
        for (logic [6:0] i = 7'h0; i < 7'h40; i += 7'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h40; j += 7'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
          end	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
          Memory[i[5:0]] = _RANDOM_MEM[33:0];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
        end	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 34'bx;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
endmodule

module SyncWriteElasticReadMemory_1(	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15
  input         clock,	// <stdin>:373:11
                io_wrEn,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input  [5:0]  io_wrAddr,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input  [1:0]  io_wrData_resp,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input  [31:0] io_wrData_user,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  output        io_rdReq_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input         io_rdReq_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input  [5:0]  io_rdReq_bits,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  input         io_rdResp_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  output        io_rdResp_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  output [1:0]  io_rdResp_bits_resp,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
  output [31:0] io_rdResp_bits_user	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:77:14
);

  wire [33:0] _mem_ext_R0_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  mem_64x34 mem_ext (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
    .R0_addr (io_rdReq_bits),
    .R0_en   (1'h1),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .W0_addr (io_wrAddr),
    .W0_en   (io_wrEn),
    .W0_clk  (clock),
    .W0_data ({io_wrData_user, io_wrData_resp})	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:119:18
  );
  assign io_rdReq_ready = io_rdResp_ready;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15
  assign io_rdResp_valid = io_rdReq_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15
  assign io_rdResp_bits_resp = _mem_ext_R0_data[1:0];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15, :119:18
  assign io_rdResp_bits_user = _mem_ext_R0_data[33:2];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:65:15, :119:18
endmodule

// VCS coverage exclude_file
module mem_64x1(	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
  input  [5:0] R0_addr,
  input        R0_en,
               R0_clk,
  output       R0_data,
  input  [5:0] W0_addr,
  input        W0_en,
               W0_clk,
               W0_data,
  input  [5:0] W1_addr,
  input        W1_en,
               W1_clk,
               W1_data
);

  reg Memory[0:63];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
  always @(posedge W0_clk) begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
    if (W0_en & 1'h1)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
      Memory[W0_addr] <= W0_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
    if (W1_en & 1'h1)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
      Memory[W1_addr] <= W1_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
    reg [31:0] _RANDOM_MEM;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
    initial begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
      `INIT_RANDOM_PROLOG_	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
      `ifdef RANDOMIZE_MEM_INIT	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
        for (logic [6:0] i = 7'h0; i < 7'h40; i += 7'h1) begin
          _RANDOM_MEM = `RANDOM;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
          Memory[i[5:0]] = _RANDOM_MEM[0];	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
        end	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 1'bx;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :217:26
endmodule

module IdParallelizeNoReadBurst(	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  input         clock,	// <stdin>:387:11
                reset,	// <stdin>:388:11
  output        s_axi_ar_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input         s_axi_ar_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [31:0] s_axi_ar_bits_addr,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [7:0]  s_axi_ar_bits_len,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [2:0]  s_axi_ar_bits_size,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [1:0]  s_axi_ar_bits_burst,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input         s_axi_ar_bits_lock,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [3:0]  s_axi_ar_bits_cache,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [2:0]  s_axi_ar_bits_prot,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [3:0]  s_axi_ar_bits_qos,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
                s_axi_ar_bits_region,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input         s_axi_r_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  output        s_axi_r_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  output [63:0] s_axi_r_bits_data,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  output [1:0]  s_axi_r_bits_resp,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  output        s_axi_r_bits_last,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
                s_axi_aw_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input         s_axi_aw_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [31:0] s_axi_aw_bits_addr,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [7:0]  s_axi_aw_bits_len,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [2:0]  s_axi_aw_bits_size,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [1:0]  s_axi_aw_bits_burst,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input         s_axi_aw_bits_lock,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [3:0]  s_axi_aw_bits_cache,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [2:0]  s_axi_aw_bits_prot,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [3:0]  s_axi_aw_bits_qos,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
                s_axi_aw_bits_region,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  output        s_axi_w_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input         s_axi_w_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [63:0] s_axi_w_bits_data,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input  [7:0]  s_axi_w_bits_strb,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input         s_axi_w_bits_last,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
                s_axi_b_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  output        s_axi_b_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  output [1:0]  s_axi_b_bits_resp,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  output [31:0] s_axi_b_bits_user,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:146:17
  input         m_axi_ar_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output        m_axi_ar_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [5:0]  m_axi_ar_bits_id,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [31:0] m_axi_ar_bits_addr,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [7:0]  m_axi_ar_bits_len,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [2:0]  m_axi_ar_bits_size,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [1:0]  m_axi_ar_bits_burst,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output        m_axi_ar_bits_lock,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [3:0]  m_axi_ar_bits_cache,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [2:0]  m_axi_ar_bits_prot,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [3:0]  m_axi_ar_bits_qos,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
                m_axi_ar_bits_region,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input         m_axi_r_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input  [5:0]  m_axi_r_bits_id,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input  [63:0] m_axi_r_bits_data,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input  [1:0]  m_axi_r_bits_resp,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input         m_axi_r_bits_last,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
                m_axi_aw_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output        m_axi_aw_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [5:0]  m_axi_aw_bits_id,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [31:0] m_axi_aw_bits_addr,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [7:0]  m_axi_aw_bits_len,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [2:0]  m_axi_aw_bits_size,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [1:0]  m_axi_aw_bits_burst,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output        m_axi_aw_bits_lock,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [3:0]  m_axi_aw_bits_cache,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [2:0]  m_axi_aw_bits_prot,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [3:0]  m_axi_aw_bits_qos,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
                m_axi_aw_bits_region,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input         m_axi_w_ready,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output        m_axi_w_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [63:0] m_axi_w_bits_data,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output [7:0]  m_axi_w_bits_strb,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  output        m_axi_w_bits_last,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input         m_axi_b_valid,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input  [5:0]  m_axi_b_bits_id,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input  [1:0]  m_axi_b_bits_resp,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
  input  [31:0] m_axi_b_bits_user	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:147:17
);

  wire       _write_bufferPayload_io_rdReq_ready;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:218:31
  wire       _write_bufferValid_ext_R0_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:217:26
  wire [5:0] _write_idList_deq_bits;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:215:24
  wire       _write_idFreelist_deq_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:214:28
  wire [5:0] _write_idFreelist_deq_bits;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:214:28
  wire       _read_bufferPayload_io_rdReq_ready;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:154:31
  wire       _read_bufferValid_ext_R0_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26
  wire [5:0] _read_idList_deq_bits;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:151:24
  wire       _read_idFreelist_deq_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:150:28
  wire [5:0] _read_idFreelist_deq_bits;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:150:28
  wire       s_axi_ar_ready_0 = m_axi_ar_ready & _read_idFreelist_deq_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:150:28, :168:38
  wire       m_axi_ar_valid_0 = _read_idFreelist_deq_valid & s_axi_ar_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:150:28, :169:44
  wire       _read_T = s_axi_ar_ready_0 & s_axi_ar_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:168:38, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire       _read_T_6 =
    _read_bufferPayload_io_rdReq_ready & _read_bufferValid_ext_R0_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26, :154:31, src/main/scala/chisel3/util/Decoupled.scala:51:35
  wire       s_axi_aw_ready_0 = m_axi_aw_ready & _write_idFreelist_deq_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:214:28, :232:38
  wire       m_axi_aw_valid_0 = _write_idFreelist_deq_valid & s_axi_aw_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:214:28, :233:44
  wire       _write_T = s_axi_aw_ready_0 & s_axi_aw_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:232:38, src/main/scala/chisel3/util/Decoupled.scala:51:35
  `ifndef SYNTHESIS	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:177:13
    always @(posedge clock) begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:177:13
      if (_read_T & ~reset & (|s_axi_ar_bits_len)) begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:177:{13,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (`ASSERT_VERBOSE_COND_)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:177:13
          $error("Assertion failed\n    at IdParallelizeNoReadBurst.scala:177 assert(s_axi.ar.bits.len === 0.U)\n");	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:177:13
        if (`STOP_COND_)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:177:13
          $fatal;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:177:13
      end
      if (_write_T & ~reset & (|s_axi_aw_bits_len)) begin	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:241:{13,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (`ASSERT_VERBOSE_COND_)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:241:13
          $error("Assertion failed\n    at IdParallelizeNoReadBurst.scala:241 assert(s_axi.aw.bits.len === 0.U)\n");	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:241:13
        if (`STOP_COND_)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:241:13
          $fatal;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:241:13
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire       _write_T_6 =
    _write_bufferPayload_io_rdReq_ready & _write_bufferValid_ext_R0_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:217:26, :218:31, src/main/scala/chisel3/util/Decoupled.scala:51:35
  IdFreeList read_idFreelist (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:150:28
    .clock     (clock),
    .reset     (reset),
    .enq_valid (_read_T_6),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .enq_bits  (_read_idList_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:151:24
    .deq_ready (_read_T),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .deq_valid (_read_idFreelist_deq_valid),
    .deq_bits  (_read_idFreelist_deq_bits)
  );
  IdList read_idList (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:151:24
    .clock     (clock),
    .reset     (reset),
    .enq_valid (m_axi_ar_ready & m_axi_ar_valid_0),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:169:44, src/main/scala/chisel3/util/Decoupled.scala:51:35
    .enq_bits  (_read_idFreelist_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:150:28
    .deq_ready (_read_T_6),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .deq_bits  (_read_idList_deq_bits)
  );
  mem_64x1 read_bufferValid_ext (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26
    .R0_addr (_read_idList_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:151:24
    .R0_en   (1'h1),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
    .R0_clk  (clock),
    .R0_data (_read_bufferValid_ext_R0_data),
    .W0_addr (_read_idList_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:151:24
    .W0_en   (_read_T_6),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (1'h0),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
    .W1_addr (m_axi_r_bits_id),
    .W1_en   (m_axi_r_valid),
    .W1_clk  (clock),
    .W1_data (1'h1)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  );
  SyncWriteElasticReadMemory read_bufferPayload (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:154:31
    .clock               (clock),
    .io_wrEn             (m_axi_r_valid),
    .io_wrAddr           (m_axi_r_bits_id),
    .io_wrData_data      (m_axi_r_bits_data),
    .io_wrData_resp      (m_axi_r_bits_resp),
    .io_wrData_last      (m_axi_r_bits_last),
    .io_rdReq_ready      (_read_bufferPayload_io_rdReq_ready),
    .io_rdReq_valid      (_read_bufferValid_ext_R0_data),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:153:26
    .io_rdReq_bits       (_read_idList_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:151:24
    .io_rdResp_ready     (s_axi_r_ready),
    .io_rdResp_valid     (s_axi_r_valid),
    .io_rdResp_bits_data (s_axi_r_bits_data),
    .io_rdResp_bits_resp (s_axi_r_bits_resp),
    .io_rdResp_bits_last (s_axi_r_bits_last)
  );
  IdFreeList write_idFreelist (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:214:28
    .clock     (clock),
    .reset     (reset),
    .enq_valid (_write_T_6),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .enq_bits  (_write_idList_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:215:24
    .deq_ready (_write_T),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .deq_valid (_write_idFreelist_deq_valid),
    .deq_bits  (_write_idFreelist_deq_bits)
  );
  IdList write_idList (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:215:24
    .clock     (clock),
    .reset     (reset),
    .enq_valid (m_axi_aw_ready & m_axi_aw_valid_0),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:233:44, src/main/scala/chisel3/util/Decoupled.scala:51:35
    .enq_bits  (_write_idFreelist_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:214:28
    .deq_ready (_write_T_6),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .deq_bits  (_write_idList_deq_bits)
  );
  mem_64x1 write_bufferValid_ext (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:217:26
    .R0_addr (_write_idList_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:215:24
    .R0_en   (1'h1),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
    .R0_clk  (clock),
    .R0_data (_write_bufferValid_ext_R0_data),
    .W0_addr (_write_idList_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:215:24
    .W0_en   (_write_T_6),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (1'h0),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
    .W1_addr (m_axi_b_bits_id),
    .W1_en   (m_axi_b_valid),
    .W1_clk  (clock),
    .W1_data (1'h1)	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  );
  SyncWriteElasticReadMemory_1 write_bufferPayload (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:218:31
    .clock               (clock),
    .io_wrEn             (m_axi_b_valid),
    .io_wrAddr           (m_axi_b_bits_id),
    .io_wrData_resp      (m_axi_b_bits_resp),
    .io_wrData_user      (m_axi_b_bits_user),
    .io_rdReq_ready      (_write_bufferPayload_io_rdReq_ready),
    .io_rdReq_valid      (_write_bufferValid_ext_R0_data),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:217:26
    .io_rdReq_bits       (_write_idList_deq_bits),	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:215:24
    .io_rdResp_ready     (s_axi_b_ready),
    .io_rdResp_valid     (s_axi_b_valid),
    .io_rdResp_bits_resp (s_axi_b_bits_resp),
    .io_rdResp_bits_user (s_axi_b_bits_user)
  );
  assign s_axi_ar_ready = s_axi_ar_ready_0;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7, :168:38
  assign s_axi_aw_ready = s_axi_aw_ready_0;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7, :232:38
  assign s_axi_w_ready = m_axi_w_ready;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_ar_valid = m_axi_ar_valid_0;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7, :169:44
  assign m_axi_ar_bits_id = _read_idFreelist_deq_bits;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7, :150:28
  assign m_axi_ar_bits_addr = s_axi_ar_bits_addr;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_ar_bits_len = s_axi_ar_bits_len;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_ar_bits_size = s_axi_ar_bits_size;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_ar_bits_burst = s_axi_ar_bits_burst;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_ar_bits_lock = s_axi_ar_bits_lock;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_ar_bits_cache = s_axi_ar_bits_cache;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_ar_bits_prot = s_axi_ar_bits_prot;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_ar_bits_qos = s_axi_ar_bits_qos;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_ar_bits_region = s_axi_ar_bits_region;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_aw_valid = m_axi_aw_valid_0;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7, :233:44
  assign m_axi_aw_bits_id = _write_idFreelist_deq_bits;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7, :214:28
  assign m_axi_aw_bits_addr = s_axi_aw_bits_addr;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_aw_bits_len = s_axi_aw_bits_len;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_aw_bits_size = s_axi_aw_bits_size;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_aw_bits_burst = s_axi_aw_bits_burst;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_aw_bits_lock = s_axi_aw_bits_lock;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_aw_bits_cache = s_axi_aw_bits_cache;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_aw_bits_prot = s_axi_aw_bits_prot;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_aw_bits_qos = s_axi_aw_bits_qos;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_aw_bits_region = s_axi_aw_bits_region;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_w_valid = s_axi_w_valid;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_w_bits_data = s_axi_w_bits_data;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_w_bits_strb = s_axi_w_bits_strb;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
  assign m_axi_w_bits_last = s_axi_w_bits_last;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/main/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.scala:143:7
endmodule

module IdParallelizeNoReadBurstTop2_6(	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:110:7
  input         clock,	// <stdin>:513:11
                reset,	// <stdin>:514:11
  output        S_AXI_ARREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input         S_AXI_ARVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [31:0] S_AXI_ARADDR,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [7:0]  S_AXI_ARLEN,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [2:0]  S_AXI_ARSIZE,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [1:0]  S_AXI_ARBURST,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input         S_AXI_ARLOCK,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [3:0]  S_AXI_ARCACHE,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [2:0]  S_AXI_ARPROT,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [3:0]  S_AXI_ARQOS,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
                S_AXI_ARREGION,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input         S_AXI_RREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  output        S_AXI_RVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  output [63:0] S_AXI_RDATA,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  output [1:0]  S_AXI_RRESP,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  output        S_AXI_RLAST,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
                S_AXI_AWREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input         S_AXI_AWVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [31:0] S_AXI_AWADDR,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [7:0]  S_AXI_AWLEN,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [2:0]  S_AXI_AWSIZE,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [1:0]  S_AXI_AWBURST,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input         S_AXI_AWLOCK,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [3:0]  S_AXI_AWCACHE,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [2:0]  S_AXI_AWPROT,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [3:0]  S_AXI_AWQOS,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
                S_AXI_AWREGION,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  output        S_AXI_WREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input         S_AXI_WVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [63:0] S_AXI_WDATA,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input  [7:0]  S_AXI_WSTRB,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input         S_AXI_WLAST,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
                S_AXI_BREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  output        S_AXI_BVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  output [1:0]  S_AXI_BRESP,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  output [31:0] S_AXI_BUSER,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:126:17
  input         M_AXI_ARREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output        M_AXI_ARVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [5:0]  M_AXI_ARID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [31:0] M_AXI_ARADDR,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [7:0]  M_AXI_ARLEN,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [2:0]  M_AXI_ARSIZE,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [1:0]  M_AXI_ARBURST,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output        M_AXI_ARLOCK,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [3:0]  M_AXI_ARCACHE,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [2:0]  M_AXI_ARPROT,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [3:0]  M_AXI_ARQOS,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
                M_AXI_ARREGION,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output        M_AXI_RREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input         M_AXI_RVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input  [5:0]  M_AXI_RID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input  [63:0] M_AXI_RDATA,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input  [1:0]  M_AXI_RRESP,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input         M_AXI_RLAST,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
                M_AXI_AWREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output        M_AXI_AWVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [5:0]  M_AXI_AWID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [31:0] M_AXI_AWADDR,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [7:0]  M_AXI_AWLEN,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [2:0]  M_AXI_AWSIZE,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [1:0]  M_AXI_AWBURST,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output        M_AXI_AWLOCK,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [3:0]  M_AXI_AWCACHE,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [2:0]  M_AXI_AWPROT,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [3:0]  M_AXI_AWQOS,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
                M_AXI_AWREGION,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input         M_AXI_WREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output        M_AXI_WVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [63:0] M_AXI_WDATA,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output [7:0]  M_AXI_WSTRB,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  output        M_AXI_WLAST,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
                M_AXI_BREADY,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input         M_AXI_BVALID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input  [5:0]  M_AXI_BID,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input  [1:0]  M_AXI_BRESP,	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
  input  [31:0] M_AXI_BUSER	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:127:17
);

  IdParallelizeNoReadBurst dut (	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:124:27
    .clock                (clock),
    .reset                (reset),
    .s_axi_ar_ready       (S_AXI_ARREADY),
    .s_axi_ar_valid       (S_AXI_ARVALID),
    .s_axi_ar_bits_addr   (S_AXI_ARADDR),
    .s_axi_ar_bits_len    (S_AXI_ARLEN),
    .s_axi_ar_bits_size   (S_AXI_ARSIZE),
    .s_axi_ar_bits_burst  (S_AXI_ARBURST),
    .s_axi_ar_bits_lock   (S_AXI_ARLOCK),
    .s_axi_ar_bits_cache  (S_AXI_ARCACHE),
    .s_axi_ar_bits_prot   (S_AXI_ARPROT),
    .s_axi_ar_bits_qos    (S_AXI_ARQOS),
    .s_axi_ar_bits_region (S_AXI_ARREGION),
    .s_axi_r_ready        (S_AXI_RREADY),
    .s_axi_r_valid        (S_AXI_RVALID),
    .s_axi_r_bits_data    (S_AXI_RDATA),
    .s_axi_r_bits_resp    (S_AXI_RRESP),
    .s_axi_r_bits_last    (S_AXI_RLAST),
    .s_axi_aw_ready       (S_AXI_AWREADY),
    .s_axi_aw_valid       (S_AXI_AWVALID),
    .s_axi_aw_bits_addr   (S_AXI_AWADDR),
    .s_axi_aw_bits_len    (S_AXI_AWLEN),
    .s_axi_aw_bits_size   (S_AXI_AWSIZE),
    .s_axi_aw_bits_burst  (S_AXI_AWBURST),
    .s_axi_aw_bits_lock   (S_AXI_AWLOCK),
    .s_axi_aw_bits_cache  (S_AXI_AWCACHE),
    .s_axi_aw_bits_prot   (S_AXI_AWPROT),
    .s_axi_aw_bits_qos    (S_AXI_AWQOS),
    .s_axi_aw_bits_region (S_AXI_AWREGION),
    .s_axi_w_ready        (S_AXI_WREADY),
    .s_axi_w_valid        (S_AXI_WVALID),
    .s_axi_w_bits_data    (S_AXI_WDATA),
    .s_axi_w_bits_strb    (S_AXI_WSTRB),
    .s_axi_w_bits_last    (S_AXI_WLAST),
    .s_axi_b_ready        (S_AXI_BREADY),
    .s_axi_b_valid        (S_AXI_BVALID),
    .s_axi_b_bits_resp    (S_AXI_BRESP),
    .s_axi_b_bits_user    (S_AXI_BUSER),
    .m_axi_ar_ready       (M_AXI_ARREADY),
    .m_axi_ar_valid       (M_AXI_ARVALID),
    .m_axi_ar_bits_id     (M_AXI_ARID),
    .m_axi_ar_bits_addr   (M_AXI_ARADDR),
    .m_axi_ar_bits_len    (M_AXI_ARLEN),
    .m_axi_ar_bits_size   (M_AXI_ARSIZE),
    .m_axi_ar_bits_burst  (M_AXI_ARBURST),
    .m_axi_ar_bits_lock   (M_AXI_ARLOCK),
    .m_axi_ar_bits_cache  (M_AXI_ARCACHE),
    .m_axi_ar_bits_prot   (M_AXI_ARPROT),
    .m_axi_ar_bits_qos    (M_AXI_ARQOS),
    .m_axi_ar_bits_region (M_AXI_ARREGION),
    .m_axi_r_valid        (M_AXI_RVALID),
    .m_axi_r_bits_id      (M_AXI_RID),
    .m_axi_r_bits_data    (M_AXI_RDATA),
    .m_axi_r_bits_resp    (M_AXI_RRESP),
    .m_axi_r_bits_last    (M_AXI_RLAST),
    .m_axi_aw_ready       (M_AXI_AWREADY),
    .m_axi_aw_valid       (M_AXI_AWVALID),
    .m_axi_aw_bits_id     (M_AXI_AWID),
    .m_axi_aw_bits_addr   (M_AXI_AWADDR),
    .m_axi_aw_bits_len    (M_AXI_AWLEN),
    .m_axi_aw_bits_size   (M_AXI_AWSIZE),
    .m_axi_aw_bits_burst  (M_AXI_AWBURST),
    .m_axi_aw_bits_lock   (M_AXI_AWLOCK),
    .m_axi_aw_bits_cache  (M_AXI_AWCACHE),
    .m_axi_aw_bits_prot   (M_AXI_AWPROT),
    .m_axi_aw_bits_qos    (M_AXI_AWQOS),
    .m_axi_aw_bits_region (M_AXI_AWREGION),
    .m_axi_w_ready        (M_AXI_WREADY),
    .m_axi_w_valid        (M_AXI_WVALID),
    .m_axi_w_bits_data    (M_AXI_WDATA),
    .m_axi_w_bits_strb    (M_AXI_WSTRB),
    .m_axi_w_bits_last    (M_AXI_WLAST),
    .m_axi_b_valid        (M_AXI_BVALID),
    .m_axi_b_bits_id      (M_AXI_BID),
    .m_axi_b_bits_resp    (M_AXI_BRESP),
    .m_axi_b_bits_user    (M_AXI_BUSER)
  );
  assign M_AXI_RREADY = 1'h1;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:110:7, :124:27
  assign M_AXI_BREADY = 1'h1;	// janberq/repos/jnbrq/hbmex-fccm2025/rtl/src/test/scala/chext/amba/axi4/full/components/IdParallelizeNoReadBurst.tb.scala:110:7, :124:27
endmodule

