# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: alveo_u55c.xdc

# Block Designs: bd/bd_top/bd_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top || ORIG_REF_NAME==bd_top} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_clk_wiz_0_0/bd_top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_clk_wiz_0_0 || ORIG_REF_NAME==bd_top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_proc_sys_reset_0_0/bd_top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_proc_sys_reset_0_0 || ORIG_REF_NAME==bd_top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_util_ds_buf_0_0/bd_top_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_util_ds_buf_0_0 || ORIG_REF_NAME==bd_top_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_util_ds_buf_1_0/bd_top_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_util_ds_buf_1_0 || ORIG_REF_NAME==bd_top_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_xdma_0_0/bd_top_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_xdma_0_0 || ORIG_REF_NAME==bd_top_xdma_0_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_smartconnect_0_1/bd_top_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_smartconnect_0_1 || ORIG_REF_NAME==bd_top_smartconnect_0_1} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_hbm_0_1/bd_top_hbm_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_hbm_0_1 || ORIG_REF_NAME==bd_top_hbm_0_1} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_proc_sys_reset_0_1/bd_top_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_proc_sys_reset_0_1 || ORIG_REF_NAME==bd_top_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_SpmvExp1_0_0/bd_top_SpmvExp1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_SpmvExp1_0_0 || ORIG_REF_NAME==bd_top_SpmvExp1_0_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_rama_0_0/bd_top_rama_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_rama_0_0 || ORIG_REF_NAME==bd_top_rama_0_0} -quiet] -quiet

# XDC: /janberq/repos/jnbrq/hbmex/fpga/vivado/alveo_u55c/SpmvExp1/SpmvExp1.gen/sources_1/bd/bd_top/bd_top_ooc.xdc
